# Generated by Django 5.0.1 on 2024-10-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='testemail@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
