# Generated by Django 5.0.1 on 2024-09-27 17:31

import account.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('publisher', 'Publisher'), ('admin', 'Admin')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.timestamp')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=account.models.dynamic_upload_path)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('address', models.TextField(blank=True, max_length=150, null=True)),
                ('sex', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Rather not say')], max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('admin_type', models.CharField(blank=True, choices=[('content_admin', 'Content Admin'), ('user_admin', 'User Admin'), ('tech_admin', 'Tech Admin'), ('financial_admin', 'Financial Admin')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('utils.timestamp',),
        ),
        migrations.CreateModel(
            name='PublisherProfile',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.timestamp')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=account.models.dynamic_upload_path)),
                ('address', models.TextField(blank=True, null=True)),
                ('publisher_manager', models.CharField(max_length=22)),
                ('company_name', models.CharField(max_length=32)),
                ('website', models.URLField()),
                ('established_year', models.PositiveSmallIntegerField()),
                ('publisher_logo', models.ImageField(blank=True, null=True, upload_to=account.models.dynamic_upload_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('utils.timestamp',),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.timestamp')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=account.models.dynamic_upload_path)),
                ('address', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('sex', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Rather not say')], max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('utils.timestamp',),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
