# Generated by Django 5.0.1 on 2024-10-14 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ebook',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='physicalbook',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image of the book', upload_to='book_covers/'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image of the book', upload_to='book_covers/'),
        ),
        migrations.AlterField(
            model_name='physicalbook',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image of the book', upload_to='book_covers/'),
        ),
    ]
