# Generated by Django 5.0.1 on 2024-09-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseCategory',
            new_name='BookType',
        ),
    ]
