# Generated by Django 5.0.1 on 2024-09-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_basecategory_booktype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent',
            new_name='book_type',
        ),
    ]
