# Generated by Django 5.0.1 on 2024-03-10 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=512)),
                ('last_name', models.CharField(max_length=512)),
                ('phone', models.CharField(blank=True, max_length=512, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('online_price', models.PositiveIntegerField()),
                ('physical_price', models.PositiveIntegerField()),
                ('online_pages_count', models.PositiveIntegerField()),
                ('physical_pages_count', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=512)),
                ('ISBN', models.CharField(max_length=225, unique=True)),
                ('description', models.TextField(blank=True, max_length=2048, null=True)),
                ('number_of_publications', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.author')),
                ('category', models.ManyToManyField(to='book.bookcategory')),
            ],
        ),
    ]
